### ISSUE TITLE
Retrieve version of REDCap associated with project

### ISSUE THREAD

**Issue by tjrivera** [sburns/PyCap#43]
It may be useful to retrieve the version of REDCap associated with a project to drive the way data is retrieved via PyCap. With the move to REDCap 6.x record IDs are not automatically exported for all forms. Specifically, if any forms are named, the API will not return the study ID unless specifically requested. 

This would be useful in controlling the exposure of other API parameters that are only available in later versions.

**Comment by sburns** [comment]
I'm glad they implemented this! A long long time ago I asked the devs at Vanderbilt to implement an API version call for this very reason, so PyCap and other libs can be more smart about how to use the API. 

This will definitely work, though it's on us to know how the API moves between X.Y.Z redcap versions.
