### ISSUE TITLE
Exporting a file returns empty string

### ISSUE THREAD

**Issue by trarbr** [sburns/PyCap#50]
Hi there,

First of all, thank you for creating PyCap. 

I'm helping set up a REDCap project where we want to run a nightly batch job that processes all the recently completed records by running them through some calculations, creating a PDF with the results and uploading them to REDCap. And that works fine! 

However, if I try to export a file, I get an empty string back. For example:

```python
fobj = open('report.pdf', 'rb')
response = project.import_file(record='1', field='po_report', fname='report.pdf', fobj=fobj)
file_content, headers = project.export_file(record='1', field='po_report')
headers
# returns {'name': 'report.pdf'}
file_content
# returns ''
len(file_content)
# returns 0
```

This is with REDCap 5.5.8, PyCap 1.0, Python 2.7.6 and Ubuntu 14.04

Note: I just tested it using curl, and this works fine:

```bash
curl -F token=${TOKEN}  -F content=file -F action=export -F record=1 -F field=po_report  ${SERVICE} > report_ex.pdf
```

**Comment by sburns** [comment]
Can you export a file that's been there for a while? I'm wondering if there's some kind of back-end job on Redcap's side that handles the actual file storage from an import API request, and that it hasn't finished by the time you request that file for export?

**Comment by trarbr** [comment]
Nope, just tried it with a file that has been up there for two days, no luck.

I also tried using requests:

```python
data = {
    'token': API_TOKEN,
    'field': 'po_report',
    'record': '1',  
    'action': 'export',
    'content': 'file'
}
r = post(API_URL, data)
r.content
# returns ''
```

**Comment by trarbr** [comment]
Just tried doing it with urllib2, and this works:
```python
from urllib import urlencode
import urllib2
d = urlencode(data)  # data from the comment above
req = urllib2.Request(API_URL, d)
response = urllib2.urlopen(req)
file = response.read()
with open('report.pdf', 'wb') as f:
  f.write(file)
# et voila, there's the pdf
```

Is it a quirk in requests?

**Comment by trarbr** [comment]
Sorry about all the spam, but it works like this:
```python
r = post(API_URL, data, stream=True)
file = r.raw.read()
with open('report.pdf', 'wb') as f:
  f.write(file)
# and there's the pdf
```
However, if I use the `iter_content()` method nothing happens:
```python
r = post(API_URL, data, stream=True)
for chunk, i in enumerate(r.iter_content()):
    print(i)
# nothing is printed
``` 
Thougts?

**Comment by trarbr** [comment]
I think the issue is caused by requests automatically decompressing the content. When using the `raw` attribute directly, it is False by default:
```python
# This is broken:
r = post(API_URL, data, stream=True)
r.raw.decode_content = True
content = r.raw.read()  # content is empty
# This works
r = post(API_URL, data, stream=True)
content = r.raw.read() # content has the entire file
```
Got the idea here: http://stackoverflow.com/a/13137873

**Comment by sburns** [comment]
Can you tell me what version of requests you're using? My best guess is there was an API change around content/raw.

**Comment by trarbr** [comment]
My version of requests is 2.5.3. I just tried it with 2.5.1 and 2.4.1 (just picking at random) with the same result.

If no one else is having this issue, I'm thinking the problem could be with the server? Apparantly requests does the automatic decompression / decoding based on the response headers. So if the server sets the wrong headers, the conversion would fail.

I'm not sure how to debug that, though

**Comment by sburns** [comment]
If you don't mind, try to go back with requests<2.0?

**Comment by trarbr** [comment]
Tried with 1.2.3, no luck

**Comment by sburns** [comment]
Think I've heard this complaint from colleagues at Vanderbilt @bud42 @byvernault

**Comment by bud42** [comment]
Hello! I think I've tracked this down to what I suspect is a bug in RedCap. It seems RedCap isn't actually compressing the file contents. I was able to have Pycap always request the contents uncompressed and that fixed the problem. I could create a PR with that modification, but not sure that's an ideal fix.

**Comment by trarbr** [comment]
Well done! I agree that it's not an ideal fix, when the problem seems to come from REDCap. What version of REDCap did you test it with?

**Comment by bud42** [comment]
Looks like the Vanderbilt REDCap is at 6.4.4. I've reported the issue to the REDCap folks. I'll update here when they respond.

**Comment by damonms** [comment]
FYI - This appears to be resolved.

**Comment by sburns** [comment]
Thanks for the heads up @damonms!
