### ISSUE TITLE
def_field no longer exporting in subforms

### ISSUE THREAD

**Issue by thephillipsequation** [sburns/PyCap#51]
"Note, no matter which fields or forms are requested, the project.def_field key will always be in the returned dicts."

This no longer appears to be true in the latest version of Redcap

Unique identifiers declared by project.def_field are no longer present in the recordset for project subforms that do not explicitly contain the 'defining field'

**Comment by tjrivera** [comment]
I've noticed this as well. In addition to project.def_field, I've also noticed `redcap_event_name` not being present.

Additionally, the API no longer seems to respect the export of any forms specifically -- instead it returns every form. 

This seems to be a problem with the API itself (not PyCap), but I'm investigating further to try and pinpoint exactly what's going on.

**Comment by sburns** [comment]
Thanks for the heads up @tjrivera! I'll finally have some time to hack on PyCap this weekend at PyCon, hopefully can hit some of these issues and cut a release to PyPI.

**Comment by tjrivera** [comment]
From REDCap's 6.0.x release notes: 

Change: When doing an API data export where a list of fields or forms are explicitly provided in the API request to REDCap, the record ID field will now only be included in the exported result if the record ID field is explicitly specified in the list of fields or if its form is explicitly specified in the list of forms. In previous versions, if *any* form or field was explicitly provided in the API request, it would return the record ID field. So for users who depend upon the Record ID field to be returned in the exported data set, they should go ahead and add the Record ID to the "fields" array parameter in their API request to maintain continuity after the upgrade to REDCap 6.0 or higher.

**Comment by tjrivera** [comment]
Should PyCap check if the associated project's version is 6.x+ and if so automatically append the `def_field`?

**Comment by thephillipsequation** [comment]
Is it possible to grab versioning info out?

I haven't had any issues when I explicitly call out form names except for the lack of the def_field. I suppose the workaround could be to get the field list and add the project.def_field and pass both in as the array.

**Comment by sburns** [comment]
> Should PyCap check if the associated project's version is 6.x+ and if so automatically append the def_field?

Sounds like a great use for the semantic versioning recently added.

**Comment by tjrivera** [comment]
@thephillipsequation you might have something like
```python
project = redcap.Project(url, api_key)
if project.redcap_version.major >= 6:
    project.export_records(forms=['demographics'], fields=[project.def_field])
else:
    project.export_records(forms=['demographics'])
```

you don't have to include the full field list

**Comment by thephillipsequation** [comment]
Thanks @tjrivera , I hadn't realized if you called a form and a field it wouldn't only export the def_field for that form. Will test this weekend

**Comment by sburns** [comment]
Maybe we don't even need the logic @tjrivera? This will be a no-op on <6.X redcap servers and >6 it will maintain backwards compatibility.
