### ISSUE TITLE
Cannot import from file

### ISSUE THREAD

**Issue by ccanales2** [sburns/PyCap#60]
Could someone please help me out? I am having issues importing a file for my study. I must be missing something.
![import file](https://cloud.githubusercontent.com/assets/15051344/10397326/15238572-6e75-11e5-9daa-b86c28a38c59.JPG)

**Comment by sburns** [comment]
Hi @ccanales2, you need to change `file_field` to the actual name of the field you're importing the file into.

**Comment by ccanales2** [comment]
Hello. When I do, I get the same message as well. I've tried all my fields. 
![capture](https://cloud.githubusercontent.com/assets/15051344/10397730/38537f78-6e77-11e5-80d0-3b337252c7ff.JPG)

**Comment by sburns** [comment]
`patientid` is most likely not a file field.

```
for field in project.metadata:
   print('{} -> {}'.format(field['field_name'], field['field_type']))
```
This loops through your project metadata (which describes your projects fields). If you have a file field in your project, one of the printed lines will say `[field name] -> file`. This is the field name you'll pass as the second argument to `project.import_file`.

**Comment by ccanales2** [comment]
Thanks Scott. Sorry to keep bothering you. 

What do I do if none of them are "files"?

**Comment by sburns** [comment]
You need to add a file field through the Redcap website in the admin panel.

**Comment by ccanales2** [comment]
Oh! Now I understand. Let me tell you what I was trying to do. I didn't want to upload a file (like an attachment to the data collection instrument) rather I wanted to upload a file that contained all the data itself. 

What I wanted to do is create a script that would download the data from one data capture system (save it as a csv file) and upload it to REDCap where it would read the file, create the fields from the first row, and the following rows would be the data. 

Do you think there is a way of doing that with the API?

**Comment by sburns** [comment]
Absolutely! I'd look at python's [csv.DictReader](https://docs.python.org/2.7/library/csv.html#csv.DictReader). This operation might look something like...

```python
import csv

with open('my_file.csv') as fobj:
    reader = csv.DictReader(fobj)  # DictReader will take the first row as the header
    data = [row for row in reader]

count = project.import_records(data)
```
Note, this assumes that one of your columns in the csv file is named the same as your default field (which I'm guessing is `patientid`?).

**Comment by ccanales2** [comment]
AH HA! Success... Thanks for your help Scott. This is going to be great for my department.
![capture](https://cloud.githubusercontent.com/assets/15051344/10402887/ffd7d634-6e95-11e5-9cd5-74ed73fa5f89.JPG)

**Comment by sburns** [comment]
Glad to help :)

**Comment by sumairhassan** [comment]
Hi Sburns and Ccanales2,

I want to do the same thing which Ccanales 2 is doing but I am getting this error "the record id field (record_id) is missing" Although in my csv file I have changed the Subj_ID to column into record_id, but it is showing the same error. Could you please help me?

![image](https://user-images.githubusercontent.com/46829161/120994203-912a2180-c784-11eb-950e-be433bc3e68c.png)

**Comment by sburns** [comment]
I would suggest printing out the first item in data and ensuring your CSV was parsed as you expected.

**Comment by sumairhassan** [comment]
Hi Sburns,

I didn't get your point. What do you mean by printing out the first item in data.  I am able to read the csv file inside the script.

I have multiple CSV and SPSS files. What I wanted to do is write a script that would read the CSV and SPSS files, create the data dictionary from files and upload its data into REDCap project.  

Do you think there is a way of doing that with the API?

Thanks

**Comment by sburns** [comment]
> Do you think there is a way of doing that with the API?

I'm not sure if there is a way to create a project via the API. 

>  What do you mean by printing out the first item in data. I am able to read the csv file inside the script.

I suggested printing out the first object you're uploading because the error implies that `record_id` is not in the dictionary that you're importing. You are likely reading the data correctly from the CSV, but the "primary key" field (`record_id`) is not set in the data that you're uploading.

**Comment by firaswehbe** [comment]
@sburns Users can get a global (one per user, project agnostic) a 64 character "Super API". You can use it to create projects, set project attributes, and do other functions like add users and mint API tokens for them.

**Comment by sburns** [comment]
> You can use it to create projects, set project attributes, and do other functions like add users and mint API tokens for them.

with great power...
